theme = "One Dark"
theme-dark = "One Dark"
foreground = "#f1f6ff"
background = "#282c34"
palette-0 = "#1e2127"
palette-1 = "#e06c75"
palette-2 = "#98c379"
palette-3 = "#d19a66"
palette-4 = "#61afef"
palette-5 = "#c678dd"
palette-6 = "#56b6c2"
palette-7 = "#abb2bf"
palette-8 = "#5c6370"
palette-9 = "#e06c75"
palette-10 = "#98c379"
palette-11 = "#d19a66"
palette-12 = "#61afef"
palette-13 = "#c678dd"
palette-14 = "#56b6c2"
privilege-notification-on-finish = true
notification-foreground = "tab-unfocused"
auto-hide-tabs-panel = "always"
font-family = "HackGen Console"
keybind = "cmd+r=rename_tab"
keybind = "cmd+up=focus_pane_up"
keybind = "cmd+left=focus_pane_left"
keybind = "cmd+right=focus_pane_right"
keybind = "cmd+shift+space=toggle_vi_mode"
keybind = "shift+enter=unbind"
keybind = "cmd+e=compose_overlay"
keybind = "cmd+shift+up=move_divider_up"
keybind = "cmd+shift+down=move_divider_down"
keybind = "cmd+shift+left=move_divider_left"
keybind = "cmd+shift+right=move_divider_right"
keybind = "cmd+9=details_tab_files"
keybind = "cmd+8=details_tab_git"
keybind = "cmd+7=details_tab_outline"
keybind = "cmd+6=details_tab_info"
keybind = "cmd+down=focus_pane_down"
adjust-cell-height = "20%"
omit-otty-prefix = true
cli-allow-overwrite = true

auto-theme-dark-mode = false
