theme = "One Light"
theme-dark = "One Dark"
foreground = "#2a2b33"
background = "#f8f8f8"
palette-0 = "#000000"
palette-1 = "#de3d35"
palette-2 = "#3e953a"
palette-3 = "#d2b67b"
palette-4 = "#2f5af3"
palette-5 = "#a00095"
palette-6 = "#3e953a"
palette-7 = "#bbbbbb"
palette-8 = "#000000"
palette-9 = "#de3d35"
palette-10 = "#3e953a"
palette-11 = "#d2b67b"
palette-12 = "#2f5af3"
palette-13 = "#a00095"
palette-14 = "#3e953a"
privilege-notification-on-finish = true
notification-foreground = "tab-unfocused"
auto-hide-tabs-panel = "always"
font-family = "HackGen Console"
keybind = "cmd+r=rename_tab"
keybind = "cmd+up=focus_pane_up"
keybind = "cmd+left=focus_pane_left"
keybind = "cmd+right=focus_pane_right"
keybind = "cmd+shift+space=toggle_vi_mode"
keybind = "shift+enter=unbind"
keybind = "cmd+e=compose_overlay"
keybind = "cmd+shift+up=move_divider_up"
keybind = "cmd+shift+down=move_divider_down"
keybind = "cmd+shift+left=move_divider_left"
keybind = "cmd+shift+right=move_divider_right"
keybind = "cmd+9=details_tab_files"
keybind = "cmd+8=details_tab_git"
keybind = "cmd+7=details_tab_outline"
keybind = "cmd+6=details_tab_info"
adjust-cell-height = "20%"
omit-otty-prefix = true
cli-allow-overwrite = true
